name: scala3-cats3

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: sbt
      - uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.11.0
      - name: Run tests
        run: sbt coverage test
